Setup New Server

diff --git a/.github/workflows/copy-and-deploying-dashboard-to-server.yml b/.github/workflows/copy-and-deploying-dashboard-to-server.yml
--- a/.github/workflows/copy-and-deploying-dashboard-to-server.yml
+++ b/.github/workflows/copy-and-deploying-dashboard-to-server.yml
@@ -79,7 +79,19 @@ jobs:
           username: ${{ secrets.GCP_VM_USERNAME }}
           key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
           script: |
-            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
+            echo "Updating resources"
+            sudo apt-get update
+            if ! command -v node &> /dev/null; then
+              echo "Node.js not found. Installing Node.js 20 and npm."
+              curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
+              sudo apt-get install -y nodejs
+            fi
+
+            echo "Node.js version:"
+            node -v
+            echo "NPM version:"
+            npm -v
+            
             cd /var/www/html/binge-admin/admin-dashboard
             npm install
           
